document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="atlas-redesign.css"><link rel="stylesheet" href="atlas-motion.css"><link rel="stylesheet" href="atlas-prompt.css">');

const types=[
  {n:'01',name:'木刻新闻插图',label:'刀痕与大黑白',note:'以大面积黑白和清晰刀痕组织画面，适合有力度的新闻叙事。',person:'woodcut-figures.png',landscape:'woodcut-palace.png',sheep:'sheep-woodcut.png',zh:'以 [主体] 为中心的木刻新闻插图，保留主体轮廓、姿态与主要构图；用粗细不一的手工刀痕和大面积纯黑组织光影，留出干净的米白纸面。黑白两色，高对比，边缘略有木纤维毛刺，旧报纸印刷质感。不要渐变、照片写实、3D 渲染、现代无衬线文字、水印或边框。',en:'Woodcut news illustration of [subject]; preserve the subject silhouette, pose, and primary composition. Shape light with bold solid-black masses and varied hand-carved gouge marks, leaving clean warm off-white paper. Strict black and white only, high contrast, slight wood-fiber roughness at edges, aged newspaper ink texture. No gradients, photorealism, 3D rendering, modern sans-serif text, watermark, or border.'},
  {n:'02',name:'钢笔排线插图',label:'线的疏密成灰阶',note:'明暗由平行线、交叉线和线距慢慢织出来。',person:'pen-figures.png',landscape:'pen-palace.png',sheep:'sheep-pen.png',zh:'以 [主体] 为中心的钢笔排线插图，保留主体比例、透视和关键细节。只用黑色墨线在白纸上塑造体积，亮部大面积留白，阴影由方向明确的平行线与交叉线逐层加密，线条随形体转折。克制的编辑插画构图，纸张可见细微纹理。不要色彩填充、模糊笔刷、铅笔涂抹、照片质感、文字、签名或水印。',en:'Pen-hatching illustration of [subject]; preserve proportions, perspective, and defining details. Model volume with black ink only on white paper: broad untouched highlights, shadows built from directional parallel hatching and crosshatching that follows form. Restrained editorial composition with subtle paper texture. No color fills, blurry brushes, pencil smudging, photo texture, text, signature, or watermark.'},
  {n:'03',name:'黑白半调网点',label:'一个颜色，无数圆点',note:'同一张网格中，点越大，眼睛读到的灰阶越深。',person:'halftone-figures.png',landscape:'halftone-palace.png',sheep:'sheep-halftone.png',zh:'将 [主体] 转成黑白报刊半调插图，保留清晰剪影与可读的明暗层次。使用规则圆形网点模拟灰阶，亮部网点稀小，暗部网点密大，网线角度统一；纸底为略泛黄的新闻纸，局部可有轻微油墨扩散和印刷颗粒。只用黑墨和纸色。不要彩色、连续平滑渐变、漫画描边、数码噪点、文字、logo 或水印。',en:'Convert [subject] into a black-and-white newspaper halftone illustration while keeping a clear silhouette and readable value structure. Use a consistent round-dot screen: tiny sparse dots in highlights, larger dense dots in shadows, one coherent screen angle. Slightly yellowed newsprint with restrained ink spread and print grain. Black ink and paper color only. No color, smooth continuous gradients, comic outlines, digital noise, text, logo, or watermark.'},
  {n:'04',name:'CMYK 四色套印',label:'四色叠成一幅图',note:'不同网角的青、品红、黄、黑小点，在远处混成完整颜色。',person:'cmyk-figures.png',landscape:'cmyk-palace.png',sheep:'sheep-cmyk.png',zh:'把 [主体] 制作成复古 CMYK 报刊四色套印图，保留原始构图、主体层级和重要细节。用青、品红、黄、黑四组可辨认的圆形网点叠色，每色使用不同网角；允许 1 至 2 像素的轻微套印偏移，边缘有真实油墨颗粒和旧纸吸墨感。颜色受限但鲜明，远看能混成完整画面。不要 RGB 霓虹光、平滑数字渐变、塑料光泽、文字、logo 或水印。',en:'Create a vintage CMYK newspaper overprint of [subject], preserving the original composition, visual hierarchy, and important details. Build color with visibly separate cyan, magenta, yellow, and black round-dot screens at distinct angles. Allow a subtle 1 to 2 pixel registration drift, authentic ink grain, and absorbent aged-paper texture. Colors are limited yet vivid and blend into a complete image from a distance. No RGB neon glow, smooth digital gradients, plastic gloss, text, logo, or watermark.'},
  {n:'05',name:'石版画',label:'油水相斥的柔雾',note:'蜡笔和墨洗留下手的力度，灰阶带着粉性和呼吸感。',person:'litho-figures.png',landscape:'litho-palace.png',sheep:'sheep-litho.png',zh:'以 [主体] 为中心的石版画，保留构图、比例与光线方向。使用油性蜡笔颗粒、墨洗和柔和的灰阶，线条可断续并带手压痕迹，暗部以层层擦染累积，留白自然呼吸。颜色限制为深黑、暖灰和纸的浅米色，石版纸有细腻粉性。不要硬边矢量色块、规则网点、照片锐化、3D 光效、文字或水印。',en:'Lithograph of [subject], preserving composition, proportions, and the direction of light. Use greasy crayon grain, ink wash, and soft values; let lines break naturally with visible hand pressure, and build dark areas through layered rubbing. Keep breathing room in the paper. Limit color to deep black, warm gray, and pale cream litho paper with a chalky surface. No hard-edged vector blocks, regular halftone dots, photo sharpening, 3D lighting, text, or watermark.'},
  {n:'06',name:'丝网印刷',label:'色块与漏墨',note:'每一种颜色是一层网版，边缘平整，色块明亮。',person:'screen-figures.png',landscape:'screen-palace.png',sheep:'sheep-screen.png',zh:'为 [主体] 创作手工丝网印刷海报，保留醒目的剪影、主要层次和负空间。使用 3 至 5 种专色，每种颜色是一层独立网版，形成平整而大胆的色块；边缘允许轻微漏印、套准偏差和墨层不均，纸张为无涂层暖白色。构图简洁、有张力。不要渐变、空气透视、照片细节、3D 效果、小字号说明文字、logo 或水印。',en:'Hand-pulled screen-print poster of [subject], preserving a strong silhouette, key layers, and negative space. Use 3 to 5 spot colors, each as a separate screen layer that forms bold flat areas. Permit slight ink skips, registration variation, and uneven ink coverage on uncoated warm-white paper. Keep the composition simple and energetic. No gradients, atmospheric perspective, photographic detail, 3D effects, small explanatory type, logo, or watermark.'},
  {n:'07',name:'蚀刻与飞尘法',label:'凹槽与随机颗粒',note:'细线来自被腐蚀的版面，灰调来自不规则的松香颗粒。',person:'etch-figures.png',landscape:'etch-palace.png',sheep:'sheep-etch.png',zh:'以 [主体] 为中心的蚀刻与飞尘法凹版画，保留细节、空间关系和静谧的光影。用被腐蚀的细密线条勾出轮廓与纹理，灰阶由不规则松香颗粒形成，暗部层次深而透明；使用深棕黑墨印在略有旧痕的厚棉纸上，压印边缘可隐约可见。不要规则圆点、纯黑大色块、彩色、数码喷溅、照片写实、文字、签名或水印。',en:'Etching and aquatint intaglio print of [subject], preserving fine detail, spatial relationships, and quiet light. Define contours and texture with delicate bitten lines; build tonal fields from irregular rosin grain, with deep yet transparent darks. Print in deep sepia-black on subtly aged heavy cotton paper, with a faint plate mark when appropriate. No regular dots, solid black graphic blocks, color, digital splatter, photorealism, text, signature, or watermark.'}
];

const specimen=(type,file,kind,extraClass='')=>`<figure class="specimen-image ${extraClass}"><img src="assets/${file}" width="1536" height="1024" alt="${type.name}${kind}案例"><figcaption>${kind}</figcaption></figure>`;
const promptLine=(lang,text,label)=>`<div class="prompt-line"><span>${lang}</span><code>${text}</code><button type="button" class="copy-prompt" data-copy="${encodeURIComponent(text)}" data-label="${label}" aria-label="${label}">${label}</button></div>`;
const promptPanel=type=>`<aside class="prompt-panel" aria-label="${type.name}作图提示词"><p>作图提示词</p>${promptLine('中文',type.zh,'复制中文')}${promptLine('EN',type.en,'Copy English')}</aside>`;
document.querySelector('#taxonomy').innerHTML=`<div class="language-heading"><p class="eyebrow">01 / 七种语言</p><h2>每一种语言，<br>都看三幅图。</h2><p>同一个世界，换一种印刷方法，线条、颗粒、黑白与颜色的说话方式都会改变。</p></div><div class="language-wall">${types.map(type=>`<article class="language-row"><header><span>${type.n}</span><div><h3>${type.name}</h3><p>${type.label}</p></div><small>${type.note}</small></header><div><div class="specimen-pair">${specimen(type,type.person,'人物图')}${specimen(type,type.landscape,'风景图')}${specimen(type,type.sheep,'羊图','sheep-sample')}</div>${promptPanel(type)}</div></article>`).join('')}</div>`;

const processCard=(number,kicker,title,accent,body,image,alt,steps,question)=>`<article class="process-card"><div class="process-copy"><p class="museum-kicker">${number} / ${kicker}</p><h3>${title}<em>${accent}</em></h3><p>${body}</p><ol class="museum-steps">${steps.map((step,index)=>`<li><b>0${index+1}</b><div><strong>${step[0]}</strong><span>${step[1]}</span></div></li>`).join('')}</ol><p class="museum-question">小观察：<strong>${question}</strong></p></div><figure><img src="assets/${image}" width="1536" height="1024" alt="${alt}"></figure></article>`;
const processCards=[
  processCard('01','凸版 / 木刻、木口木刻、麻胶版','高起来的地方，','才会印到纸上。','先把不要的地方刻低。滚筒只碰得到高高的图案，像给一枚印章上色。','process-relief.png','凸版木刻的三步工艺图：在凸起的木板上滚墨，再用纸压印，得到黑色叶子图案。',[['刻出高低','图案留在高处，背景被刻低。'],['滚墨','油墨只滚到凸起的图案表面。'],['压到纸上','纸一压，叶子的形状就被带走了。']],'木刻的黑色大块和刀痕，为什么看起来很有力量？'),
  processCard('02','凹版 / 蚀刻、干刻、飞尘法','油墨躲进沟里，','纸把它吸出来。','凹版和印章正好相反。细线和小坑是藏墨的地方，版面表面要擦干净。','process-intaglio.png','凹版蚀刻的三步工艺图：墨进入铜板凹槽，擦掉表面油墨，再用湿纸和压印机印出线条。',[['让凹槽喝饱墨','油墨被推入腐蚀或刻出的细沟。'],['擦掉表面','留下沟里的墨，铜板表面露出来。'],['湿纸压进去','强大的压力让纸贴进沟槽，把墨带走。']],'为什么凹版线条常常很细、很有光泽？'),
  processCard('03','平版 / 石版画、现代胶印','石头是平的，','油和水不做朋友。','石版没有高和低。秘密在材料的脾气：水喜欢空白处，油墨只喜欢油性画过的图案。','process-planographic.png','平版石版画的三步工艺图：在平整石头上画油性图案，水留在空白处，油墨转印出月亮和星星。',[['用油性笔画图','在平整石头上画出亲油的图案。'],['先上水，再上墨','空白处留水拒绝油墨，图案抓住油墨。'],['把图像转到纸上','压印后，柔和的笔触就出现了。']],'为什么石版画很适合画云雾和手绘灰调？'),
  processCard('04','孔版 / 丝网印刷、漏版','能通过的网孔，','就是颜色的门。','把不想印的地方封住，留下图案的开口。刮板一推，油墨就从细网孔穿到纸上。','process-stencil.png','丝网孔版印刷的三步工艺图：在网版上遮住不要印的地方，用刮板推油墨穿过开孔，印出红色小鱼。',[['做一张网版','遮住背景，图案区域保持通透。'],['刮板推墨','油墨从未封住的网孔挤过去。'],['一色一层','想要更多颜色，就换另一张网版再印。']],'为什么丝网印刷的颜色常常又平又亮？')
];
document.querySelector('#process').innerHTML=`<div class="process-heading"><p class="eyebrow">02 / 工艺实验室</p><h2>四种转印关系，<br>一次看完整。</h2><p>看图时，请沿着每张图里的箭头走。油墨找到自己的位置，再被转移到纸上。</p></div><div class="process-wall">${processCards.join('')}</div><div class="screening-exhibit"><div><p class="eyebrow">报纸插图的小展柜</p><h3>照片，怎么变成小点？</h3><p>报纸和杂志常用网点制造明暗。点很小，近看像棋盘，退远一点，眼睛就会把它们合成一张有灰阶的图。</p></div><div class="screening-visual"><div class="screening-panel"><b>黑白半调网点</b><div class="tone-demo" aria-label="由小到大的黑色网点示意"><i class="tone t1"></i><i class="tone t2"></i><i class="tone t3"></i><i class="tone t4"></i></div><small>点越大，纸被盖住得越多，看起来越深。</small></div><div class="screening-panel"><b>四色套印</b><div class="museum-rosette" aria-label="青品红黄黑四色网点叠印示意"><i class="cyan"></i><i class="magenta"></i><i class="yellow"></i><i class="black"></i></div><small>四种颜色的小点交叠，远看会混成丰富的颜色。</small></div></div></div>`;

document.querySelector('#cases').remove();

const writeClipboard=async text=>{
  if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return}
  const field=document.createElement('textarea');field.value=text;field.style.position='fixed';field.style.opacity='0';document.body.appendChild(field);field.select();document.execCommand('copy');field.remove();
};
document.addEventListener('click',async event=>{
  const button=event.target.closest('.copy-prompt');
  if(!button)return;
  const label=button.dataset.label;
  try{await writeClipboard(decodeURIComponent(button.dataset.copy));button.textContent=label==='复制中文'?'已复制':'Copied'}catch{button.textContent='复制失败'}
  setTimeout(()=>{button.textContent=label},1200);
});

const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reduceMotion){
  document.documentElement.classList.add('motion-ready');
  const reveals=[...document.querySelectorAll('.language-heading,.process-heading,.language-row,.process-card,.screening-exhibit,.magnifier,.cta')];
  reveals.forEach((element,index)=>{element.classList.add('reveal');element.style.setProperty('--reveal-delay',`${Math.min(index%4,3)*55}ms`)});
  if('IntersectionObserver' in window){
    const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -24px'});
    reveals.forEach(element=>observer.observe(element));
  }else reveals.forEach(element=>element.classList.add('is-visible'));
}
